language: node_js

script:
  - ./build.sh
  - node_modules/.bin/istanbul cover node_modules/.bin/_mocha -- --reporter mocha-lcov-reporter
  - node script/lcov-transform.js coverage/lcov.info `pwd`/ . | node_modules/.bin/coveralls

node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "iojs"
