language: node_js

script:
  - ./bootstrap.sh
  - node_modules/.bin/istanbul cover node_modules/.bin/_mocha -- --reporter mocha-lcov-reporter
  - node script/lcov-transform.js coverage/lcov.info `pwd`/ bin lib | node_modules/.bin/coveralls
node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "iojs"
